
package Jframe;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class LaporanMobil extends javax.swing.JFrame {

    DefaultTableModel model;
    
    public LaporanMobil() {
        initComponents();
        setTitle("Laporan Mobil Tersedia");
        setData();
    }

    
    public void setData() {
        try {
            Connection con = DBConnection.getConnection();
            Statement st = con.createStatement();

            // Query untuk mengambil data mobil yang tersedia
            String query = "SELECT id_mobil, merk, model, tipe, status FROM mobil WHERE status = 'Tersedia'";
            ResultSet rs = st.executeQuery(query);

            // Mendapatkan model tabel
            DefaultTableModel model = (DefaultTableModel) tbl_mobil.getModel();
            model.setRowCount(0); // Membersihkan tabel sebelum memasukkan data baru

            while (rs.next()) {
                String idMobil = rs.getString("id_mobil");
                String merk = rs.getString("merk");
                String modelMobil = rs.getString("model");
                String tipe = rs.getString("tipe");
                String status = rs.getString("status");

                // Menambahkan data ke tabel
                model.addRow(new Object[]{idMobil, merk, modelMobil, tipe, status});
            }

            con.close(); // Menutup koneksi setelah selesai
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal memuat data mobil: " + e.getMessage());
        }
    }

    public void CariData() {
        clearTable(); // Membersihkan tabel sebelum memasukkan hasil pencarian
        String cari = txt_cariMobil.getText(); // Mengambil kata kunci pencarian dari TextField

        try {
            Connection con = DBConnection.getConnection();

            // Query pencarian berdasarkan kata kunci, hanya untuk mobil yang tersedia
            String query = "SELECT id_mobil, merk, model, tipe, status FROM mobil " +
                           "WHERE status = 'Tersedia' AND " +
                           "(id_mobil LIKE ? OR merk LIKE ? OR model LIKE ? OR tipe LIKE ? OR status LIKE ?)";
            PreparedStatement pst = con.prepareStatement(query);

            // Menambahkan wildcard "%" untuk pencarian
            pst.setString(1, "%" + cari + "%");
            pst.setString(2, "%" + cari + "%");
            pst.setString(3, "%" + cari + "%");
            pst.setString(4, "%" + cari + "%");
            pst.setString(5, "%" + cari + "%");

            ResultSet rs = pst.executeQuery();

            // Mendapatkan model tabel
            DefaultTableModel model = (DefaultTableModel) tbl_mobil.getModel();
            model.setRowCount(0); // Membersihkan tabel sebelum memasukkan data baru

            while (rs.next()) {
                String idMobil = rs.getString("id_mobil");
                String merk = rs.getString("merk");
                String modelMobil = rs.getString("model");
                String tipe = rs.getString("tipe");
                String status = rs.getString("status");

                // Menambahkan data ke tabel
                model.addRow(new Object[]{idMobil, merk, modelMobil, tipe, status});
            }

            con.close(); // Menutup koneksi setelah selesai
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal mencari data mobil: " + e.getMessage());
        }
    }

    private void clearTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_mobil.getModel();
        model.setRowCount(0); // Menghapus semua baris pada tabel
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_cariMobil = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_mobil = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(51, 23, 185));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 23, 185));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mobility.png"))); // NOI18N
        jLabel4.setText("Laporan Mobil Tersedia");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        jLabel7.setBackground(new java.awt.Color(102, 102, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Back_40Px2.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 15)); // NOI18N
        jLabel8.setText("Cari :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 100, 30));

        txt_cariMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariMobilActionPerformed(evt);
            }
        });
        txt_cariMobil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariMobilKeyReleased(evt);
            }
        });
        jPanel1.add(txt_cariMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 240, 30));

        tbl_mobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Merk", "Model", "Tipe", "Status"
            }
        ));
        tbl_mobil.setColorBackgoundHead(new java.awt.Color(96, 123, 179));
        tbl_mobil.setRowHeight(25);
        tbl_mobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mobilMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_mobil);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 820, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 620));

        setSize(new java.awt.Dimension(936, 628));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        HomePage HomePage = new HomePage();
        HomePage.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void txt_cariMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariMobilActionPerformed

    private void txt_cariMobilKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariMobilKeyReleased
        CariData();
    }//GEN-LAST:event_txt_cariMobilKeyReleased

    private void tbl_mobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mobilMouseClicked

    }//GEN-LAST:event_tbl_mobilMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaporanMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaporanMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaporanMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanMobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LaporanMobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private rojerusan.RSTableMetro tbl_mobil;
    private javax.swing.JTextField txt_cariMobil;
    // End of variables declaration//GEN-END:variables
}
