/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Jframe;

//import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.JOptionPane;


public class LogIn extends javax.swing.JFrame {

    public LogIn() {
        initComponents();
        setTitle("Login"); // Menambahkan judul aplikasi
        
    }

    //validatelogin
    public boolean validateLogin(){
        String username = txt_username.getText();
        String password = txt_password.getText();
        
        if (username.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter username");
            return false;
        }
        
        if (password.equals("")) {
            JOptionPane.showMessageDialog(this, "Please enter password");
            return false;
        }
         return true;
    }
    public void login() {
    String username = txt_username.getText();
    String password = txt_password.getText();

    try {
        Connection con = DBConnection.getConnection();
        PreparedStatement pst = con.prepareStatement("SELECT username, password FROM users WHERE username = ? AND password = ?");
        pst.setString(1, username);
        pst.setString(2, password);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            // Jika login berhasil
            JOptionPane.showMessageDialog(this, "Login Berhasil");
            HomePage homepage = new HomePage();
            homepage.setVisible(true);
            this.setVisible(false); 
        } else {
            JOptionPane.showMessageDialog(this, "Incorrect username or password");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username = new javax.swing.JTextField();
        jdl_username = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jdl_password = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        button_login2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jdl_username1 = new javax.swing.JLabel();
        button_login3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 270, 30));

        jdl_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jdl_username.setText("Daftar Akun?");
        getContentPane().add(jdl_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 90, 20));

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 270, 30));

        jdl_password.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jdl_password.setText("Password");
        getContentPane().add(jdl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel9.setText("Login");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        button_login2.setBackground(new java.awt.Color(204, 204, 255));
        button_login2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        button_login2.setText("Log In");
        button_login2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                button_login2CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        button_login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_login2ActionPerformed(evt);
            }
        });
        getContentPane().add(button_login2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 120, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mobilin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 430, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Selamat Datang di");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 160, 30));

        jdl_username1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jdl_username1.setText("Username");
        getContentPane().add(jdl_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 20));

        button_login3.setBackground(new java.awt.Color(204, 204, 255));
        button_login3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        button_login3.setText("Log In");
        button_login3.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                button_login3CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        button_login3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_login3ActionPerformed(evt);
            }
        });
        getContentPane().add(button_login3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 120, 30));

        jButton1.setText("Daftar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 90, 30));

        setSize(new java.awt.Dimension(456, 505));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
        validateLogin();
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed

    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameFocusLost

    private void button_login2CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_button_login2CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_button_login2CaretPositionChanged

    private void button_login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_login2ActionPerformed
        if (validateLogin()){
            login();
        }
    }//GEN-LAST:event_button_login2ActionPerformed

    private void button_login3CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_button_login3CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_button_login3CaretPositionChanged

    private void button_login3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_login3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_login3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          // TODO add your handling code here:
        Register log = new Register();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_login2;
    private javax.swing.JButton button_login3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jdl_password;
    private javax.swing.JLabel jdl_username;
    private javax.swing.JLabel jdl_username1;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    private void Connect() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void setIconImage() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
